### ISSUE TITLE
Great Library. Thanks

### ISSUE THREAD

**Issue by Phystro** [apexcharts/Blazor-ApexCharts#117]
I'm loving your library, really saved me in our project. The fact that I don't have to handle the javascript side and the freedom of customization is awesome. Life save library. We have tried several libraries and this is the first that didnt feel as if I had to fight it to fit our project.

**Comment by thismaker** [comment]
I couldn't agree more.

**Comment by joadan** [comment]
Thank you so much!

Feedback like this is especially heart warming because I don't use the wrapper myself in any projects.
I made the wrapper as a way to learn blazor javascript interop and it is my first open source project.

After joining the Apexchart organization we are commited to continue to support the wrapper.

**Comment by Vinayak90** [comment]
Thank you for the great library and your efforts to make it delightful.
