### ISSUE TITLE
[Help] Double x-axis labels

### ISSUE THREAD

**Issue by PaulKristoffersson** [apexcharts/Blazor-ApexCharts#128]
Hey! I am trying to create a line chart with double annotations on the x-axis. Currently i am printing the weekly summary of scores per day, and in turn the x-axis labels are the week numbers. I would like to either create a second axis of labels that consists of the months or instead of printing the weeks print the corresponsing month. Here is a picture of how it looks right now. 

![graf](https://user-images.githubusercontent.com/57681017/178679376-72fe2944-1a30-450c-b035-4873036f57a0.png)

**Comment by PaulKristoffersson** [comment]
![image](https://user-images.githubusercontent.com/57681017/179189275-6e9dbd2b-f126-4d07-b16e-4f643fe27843.png)

**Comment by PaulKristoffersson** [comment]
![Githubgraf](https://user-images.githubusercontent.com/57681017/179190513-09615f0e-4658-4a8b-8ab0-b5754c3f16c6.png)

So i pretty much want it to look like this, having the months span under the week numbers.  If this is not possible another way i could do it is by having the week numbers in the ToolTipX, however i can't figure out how to change the format and text of the tooltip.

**Comment by joadan** [comment]
Hi,

My initial idea was to use the XAxis group function https://apexcharts.github.io/Blazor-ApexCharts/features/axis#xaxis%20groups
But it will be a problem because the weeks can span multiple months.

If you want to go with the tooltip option you could make your custom tooltip, https://apexcharts.github.io/Blazor-ApexCharts/features/tooltip
