### ISSUE TITLE
Add samples for formatters and tooltip templates

### ISSUE THREAD

**Issue by joadan** [apexcharts/Blazor-ApexCharts#33]

**Comment by AzureGulf** [comment]
Have just started using your charts today - looks good.
Please add a few simple examples for things like formatting the Y axis labels - I've tried formatting with standard C# strings such as "N0" (to get zero decimal places and comma delimiter) but no luck, so far...
And, is the YValue/Aggregrate always 'decimal', can't I have other value types on the Y axis?

**Comment by joadan** [comment]
The formaters are javascript functions, please see the samples in the Apex documentation, https://apexcharts.com/docs/formatting-axes-labels/

The [Line](https://apexcharts.github.io/Blazor-ApexCharts/line-charts) samples Datetime do contains examples of Y value tooltip.

The data type for Y axis is decimal, but you should be able convert a numeric type to it. Please let me know if you have a use case where this is not working.

For zeros decimal places you can use the option DecimalsInFloat, this is also in the Datetime sample

```
options.Yaxis.Add(new YAxis
            {
                DecimalsInFloat = 0,
                Labels = new AxisLabels { Rotate = -45, Style = new AxisLabelStyle { FontSize = "10px" } },
                Title = new AxisTitle { Text = "Value", Style = new AxisTitleStyle { FontSize = "14px", Color = "lightgrey" } }
            });
```

**Comment by AzureGulf** [comment]
Thanks for your comment and pointers.
Most Y axes can be formatted to the local culture, so "en-us" would show a (currency) value of 300000.00 as $300,000.00 whereas in "fr" it would be €300 000,00 and so on...

Numeric values should also follow the same formatting rules (for example as defined by the N formatter). I'd also expect numbers to be similarly formatted within the tooltip.

My comment on the Y axis type was simply to question why is was fixed as decimal - what happens if you want to invert the X and Y axes? Say, as per your first Line chart example, so that Y axis is now the Country and X is the value.

**Comment by joadan** [comment]
I agree on the formatters, only having javascript functions is really limiting. I'll raise a separate issue for tracking this.

For the Y decimal value, should not be a problem, if you want to invert the Axis you set up the chart as normal and then flip the axis, see Horizontal demo here https://apexcharts.github.io/Blazor-ApexCharts/bar-charts

**Comment by AzureGulf** [comment]
> For the Y decimal value, should not be a problem, if you want to invert the Axis you set up the chart as normal and then flip the axis, see Horizontal demo here https://apexcharts.github.io/Blazor-ApexCharts/bar-charts
thanks - I missed that!

**Comment by joadan** [comment]
Clean up
